### PR TITLE
revamp setup files

### PR DESCRIPTION
**Pull request by samuelstjean**
Another way to fix the dependencies version thing, this one is a bit cleaner since it downloads and builds separately from the user installed version, ensuring the source/wheels are working on very old versions of stuff.

### CODE REVIEW

**Comment by samuelstjean** [comment]
Also fix #1 on the side normally

**Comment by gdurif** [comment]
Thanks @samuelstjean :+1: 

I am able to install and run the test with this version on my Linux machine with a clean virtual env (Python 3.8.10).

@daducci Would you happen to have a machine with an older setup (Python<3.8) to test the installation ?

**Comment by gdurif** [comment]
It works with Python 3.7.11 (which installs Numpy v1.21.5 instead of v1.22+) 

```
$ python -V 
Python 3.7.11
$ pip install .
Processing /home/drg/work/dev/project/spams/spams-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow>=6.0
  Downloading Pillow-9.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 2.5 MB/s eta 0:00:00
Collecting Cython>=0.29
  Downloading Cython-0.29.28-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 2.5 MB/s eta 0:00:00
Collecting numpy>=1.12
  Downloading numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 2.6 MB/s eta 0:00:00
Collecting six>=1.12
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting scipy>=1.0
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 2.3 MB/s eta 0:00:00
Building wheels for collected packages: spams
  Building wheel for spams (pyproject.toml) ... done
  Created wheel for spams: filename=spams-2.6.3.1-cp37-cp37m-linux_x86_64.whl size=5974248 sha256=be3cec4fdfe5b155792bc253ec1368614a393775d0aa2180eca09b1a41a625f3
  Stored in directory: /home/xxxxxxxx
Successfully built spams
Installing collected packages: six, Pillow, numpy, Cython, scipy, spams
Successfully installed Cython-0.29.28 Pillow-9.0.1 numpy-1.21.5 scipy-1.7.3 six-1.16.0 spams-2.6.3.1
```

I am merging this and uploading PyPI. Thanks again @samuelstjean

**Comment by daducci** [comment]
> Thanks @samuelstjean 👍
> 
> I am able to install and run the test with this version on my Linux machine with a clean virtual env (Python 3.8.10).
> 
> @daducci Would you happen to have a machine with an older setup (Python<3.8) to test the installation ?

I can ask Simona who has such a machine! Thanks!

**Pull request merged**
